

name: Doc Evlib

on: workflow_dispatch

jobs:
    doc_evlib:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - run: ./gradlew Evlib:Evlib:dokkaHtml

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./Evlib/Evlib/build/dokka
