

name: Doc Evlib

on: workflow_dispatch

jobs:
    doc_evlib:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                ref: master

            - name: Run dokka
              uses: jojo243/android-gradle-action@2.1.3
              with:
                script: Evlib:Evlib:dokkaHtml

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./Evlib/Evlib/build/dokka
